import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans, Poppins } from "next/font/google";
import "./globals.css";
import { AppHeader } from "@/components/AppHeader";
import { StoreWrapper } from "@/components/storeWrapper";
import { AppFooter } from "@/components/AppFooter";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { LanguageWrapper } from "@/components/LanguageWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const dm_sans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  return (
    <NextIntlClientProvider messages={messages}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${dm_sans.variable} ${poppins.variable} antialiased`}
        >
          <StoreWrapper>
            <LanguageWrapper>
              <AppHeader />
              {children}
              <AppFooter />
            </LanguageWrapper>
          </StoreWrapper>
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
